name: Docker build
on: push
jobs:
  push_to_registry:
    name: Push Docker image to my package registry
    runs-on: ubuntu-latest
    steps:
      - name: Setup k8s config
        shell: bash
        run: |
          mkdir /.kube
          echo "${{secrets.KUBECONFIG}}" > ${{vars.KUBECONFIG}}
          curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl


      # Check out repo
      - name: Check out the repo
        uses: actions/checkout@v4 #.1.1                            

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
      #     driver-opts: |
      #       namespace=gitea
      #       rootless=true

      # # Log in to registry
      # - name: Log in to my package registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: git.labs.andrewpjackson.com
      #     username: username
      #     password: my-pat
      
      # # Build and push
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: false
      #     tags: user/app:latest




# name: 🧪 Test building with Kaniko

# on: push

# jobs:
#   build:
#     # runs-on: [kaniko-worker] # our new runner set
#     container:
#       image: git.labs.andrewpjackson.com/healingorganics/kaniko:debug # the kaniko image
#     permissions:
#       contents: read # read the repository
#       # packages: write # push to GHCR, omit if not pushing to GitHub's container registry

#     steps:
#       - name: Build and push container test
#         shell: shell
#         run: |
#           # Write config file, change to your destination registry
#           AUTH=$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64)
#           echo "{\"auths\": {\"ghcr.io\": {\"auth\": \"${AUTH}\"}}}" > /kaniko/.docker/config.json

#           # Configure git
#           export GIT_USERNAME="kaniko-bot"
#           export GIT_PASSWORD="${{ secrets.GITHUB_TOKEN }}" # works for GHEC or GHES container registry

#           # Build and push (sub in your image, of course)
#           /kaniko/executor --dockerfile="./custom-images/ubuntu-22.04/Dockerfile" \
#             --context="." \
#             --destination="git.labs.andrewpjackson.com/healingorganics/kairos-images:test" \
#             --push-retry 5
